# Generated by Django 5.0.2 on 2024-02-19 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_quote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='qoute_text',
            new_name='quote_message',
        ),
    ]
